dynamic_input/urls.py
from django.urls import path

from . import views


app_name = 'inputs'

urlpatterns = [
    path('dynamic/', views.dynamic_inputs, name='dynamic_inputs'),
    path('result/', views.inputs_result, name='inputs_result'),
]

task_main/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('inputs/', include('dynamic_input.urls', namespace='inputs'))
]

dynamic_input/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class InputResult(models.Model):

    result = JSONField()

dynamic_input/views.py
import json
from django.shortcuts import render
from django.http import HttpResponse

from .models import InputResult


def dynamic_inputs(request):
    if request.method == "POST":
        result_json = json.loads(request.body)
        InputResult.objects.create(result=result_json)
        return HttpResponse(status=200)
    else:
        return render(request, 'dynamic_input/inputs.html')


def inputs_result(request):
    result_json = {}
    json_fields = InputResult.objects.all()
    for row in json_fields:
        result_json[f"JSON{row.id}"] = row.result
    result = json.dumps(result_json)
    return render(request, 'dynamic_input/results.html', {'json': result, })

dynamic_input/templates/dynamic_input/inputs.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Inputs</title>
</head>
<body>
    <script src="{% static 'js/add.js' %}"></script>
    <div align="center">
        <form id="main-form">
            {% csrf_token %}
            <label for="name1">name1</label>
            <input type="text" class="name" id="name1" name="input-form">
            <input type="button" class="button" id="button1" value="Добавить" name="input-form" onclick="addInput()">
            <input type="button" class="button" id="button2" value="Отправить" name="input-form" onclick="submitForm()">
        </form>
        <a href="{% url 'inputs:inputs_result' %}">Результат</a>
    </div>
</body>
</html>

dynamic_input/templates/dynamic_input/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <p>{{ json }}</p>
    <a href="{% url 'inputs:dynamic_inputs' %}">Назад</a>
</body>
</html>